### ISSUE TITLE
Does this library support upload and download of files?

### ISSUE THREAD

**Issue by darcome** [roxxel/TeleSharp#3]
Hi, 

I'd like to know if this library supports file upload and download, so that it would be possible to build a storage manager app.

Thanks in advance!

**Comment by roxxel** [comment]
Hi there! Yes, it supports downloading and uploading files. Although it's a bit tricky (as everything in tdlib). If you trying to make regular bot I'd suggest you to take a look at my another project [TeleSharpX](https://github.com/roxxel/telesharpx]

**Comment by darcome** [comment]
Hi! If I am not wrong with a bot, you can only upload 50mb at a time, therefore it wouldn’t be enough.
I also took a look at the code but I only found SendPhotoAsync.
Can you please give me hints on how I can upload and download files in the “saved messages” chat?

Thanks in advance!

**Comment by roxxel** [comment]
> Hi! If I am not wrong with a bot, you can only upload 50mb at a time, therefore it wouldn’t be enough. I also took a look at the code but I only found SendPhotoAsync. Can you please give me hints on how I can upload and download files in the “saved messages” chat?
> 
> Thanks in advance!

Hi! You'd have to use RawClient property on TelegramClient, which exposes every method that available
example:
```cs
await _client.RawClient.SendMessageAsync(_client.CurrentUser.Id,
    inputMessageContent: new TdApi.InputMessageContent.InputMessageDocument()
{
    Document = new TdApi.InputFile.InputFileLocal()
    {
        Path = "Path to file"
    }
});
```

If you have any other questions consider joining [discord](https://discord.gg/yJXXx5zk2W) server, that would speed up this process a bit

**Comment by darcome** [comment]
Thank you very much!

If I'll have more questions I'll join the discord server for sure!
